version: "3.8"

services:
  wine:
    build: .
    container_name: 3DSRNGTool
    restart: unless-stopped
    volumes:
      - rngtool:/root/3DSRNGTool
    ports:
      - "8080:8080"

volumes:
  rngtool: